# Create a deployment named nginx in the qq2 namespace using the nginx image with 3 replicas.

# 
# create namespace: k create ns qq2
# run this command: k create deployment nginx --image=nginx --replicas=3 -n qq2 --dry-run -o yaml > nginx.yaml
# run this command: k apply -f nginx.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
  namespace: qq2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}