Deploy  postgres by using Deployment with the following image:

https://hub.docker.com/_/postgres

Use proper ConfigMap, Secret, Persistent Volume/StorageClass, PersistenVolumeClaim ,  Service


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres-deployment
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-deployment
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgress-claim
      containers:
      - image: postgres
        name: postgres
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data/"
            name: data
            subPath: pgdata
        ports:
        - containerPort: 8080
        resources: {}
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgress-claim
spec:
  storageClassName: postgres-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
      
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage
provisioner: docker.io/hostpath
volumeBindingMode: Immediate

---

apiVersion: v1
data:
  POSTGRES_DB: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_USER: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: postgres-secret 