# Deploy a pod named nginx using the nginx image in the qq3 namespace with a liveness and readiness probe for port 80.

# Pod: nginx 
# Namespace: qq3
# Image: nginx
# Liveness Probe: port: 80 
# Readiness Probe: port: 80


apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: qq3
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 10