# Create a configuration file to create a pod of redis with redis image and 6 replicas with label app_env_stage=dev. The file should be placed under /opt/cka

# cd /opt
# mkdir cka
# k create deployment redis --image=redis:latest --port=80 --replicas=6 --dry-run -o yaml > redis.yaml
# add label app_env_stage: dev


apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
    app_env_stage: dev
  name: redis
spec:
  replicas: 6
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 80
        resources: {}
status: {}